---
abstract: 'Perl bindings for SWT'
author:
  - 'Ahmad M. Zawawi, C<< <ahmad.zawawi at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SWT
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
